print()
print("Zahlenvergleich")
print("===============")
print()
a = int(input("Gib die erste Zahl ein: "))
b = int(input("Gib die zweite Zahl ein: "))
c = int(input("Gib die dritte Zahl ein: "))
print()
max_num = max(a, b, c)
min_num = min(a, b, c)
print()
print("Die größte Zahl ist:", max_num)
print("Die kleinste Zahl ist:", min_num)
print()
print("Programmende")
print()